/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdslink_mpmerge_MPMergeJNI */

#ifndef _Included_com_gdslink_mpmerge_MPMergeJNI
#define _Included_com_gdslink_mpmerge_MPMergeJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdslink_mpmerge_MPMergeJNI
 * Method:    test
 * Signature: (Lcom/gdslink/mpmerge/MPWrapData;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdslink_mpmerge_MPMergeJNI_test
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
