
package com.gdslink.mpmerge.santander.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://www.gruposantander.es/webservices/genericFault")
public class GetCurrentBureauDataFault
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.gdslink.mpmerge.santander.soap.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public GetCurrentBureauDataFault(String message, com.gdslink.mpmerge.santander.soap.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public GetCurrentBureauDataFault(String message, com.gdslink.mpmerge.santander.soap.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.gdslink.mpmerge.santander.soap.Exception
     */
    public com.gdslink.mpmerge.santander.soap.Exception getFaultInfo() {
        return faultInfo;
    }

}
