
package com.gdslink.mpmerge.santander.soap;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MTXSOVWS_Service", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", wsdlLocation = "/WEB-INF/wsdl/MTXSOVWS_v1.wsdl")
public class MTXSOVWSService
    extends Service
{

    private final static URL MTXSOVWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MTXSOVWSSERVICE_EXCEPTION;
    private final static QName MTXSOVWSSERVICE_QNAME = new QName("http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", "MTXSOVWS_Service");

    static {
        MTXSOVWSSERVICE_WSDL_LOCATION = com.gdslink.mpmerge.santander.soap.MTXSOVWSService.class.getResource("/WEB-INF/wsdl/MTXSOVWS_v1.wsdl");
        WebServiceException e = null;
        if (MTXSOVWSSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/WEB-INF/wsdl/MTXSOVWS_v1.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MTXSOVWSSERVICE_EXCEPTION = e;
    }

    public MTXSOVWSService() {
        super(__getWsdlLocation(), MTXSOVWSSERVICE_QNAME);
    }

    public MTXSOVWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MTXSOVWSSERVICE_QNAME, features);
    }

    public MTXSOVWSService(URL wsdlLocation) {
        super(wsdlLocation, MTXSOVWSSERVICE_QNAME);
    }

    public MTXSOVWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MTXSOVWSSERVICE_QNAME, features);
    }

    public MTXSOVWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MTXSOVWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MTXSOVWSPortTypeHTTP
     */
    @WebEndpoint(name = "MTXSOVWSPortHTTP")
    public MTXSOVWSPortTypeHTTP getMTXSOVWSPortHTTP() {
        return super.getPort(new QName("http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", "MTXSOVWSPortHTTP"), MTXSOVWSPortTypeHTTP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MTXSOVWSPortTypeHTTP
     */
    @WebEndpoint(name = "MTXSOVWSPortHTTP")
    public MTXSOVWSPortTypeHTTP getMTXSOVWSPortHTTP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", "MTXSOVWSPortHTTP"), MTXSOVWSPortTypeHTTP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MTXSOVWSSERVICE_EXCEPTION!= null) {
            throw MTXSOVWSSERVICE_EXCEPTION;
        }
        return MTXSOVWSSERVICE_WSDL_LOCATION;
    }

}
