
package com.gdslink.mpmerge.santander.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTXSOVWSPortTypeHTTP", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTXSOVWSPortTypeHTTP {


    /**
     * 
     * @param getCurrentBureauDataInputPart
     * @return
     *     returns com.gdslink.mpmerge.santander.soap.GetCurrentBureauDataResponse
     * @throws GetCurrentBureauDataFault
     */
    @WebMethod(action = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1/getCurrentBureauData")
    @WebResult(name = "getCurrentBureauDataResponse", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getCurrentBureauData_OutputPart")
    public GetCurrentBureauDataResponse getCurrentBureauData(
        @WebParam(name = "getCurrentBureauData", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getCurrentBureauData_InputPart")
        GetCurrentBureauData getCurrentBureauDataInputPart)
        throws GetCurrentBureauDataFault
    ;

    /**
     * 
     * @param getRawAllBureausInputPart
     * @return
     *     returns com.gdslink.mpmerge.santander.soap.GetRawAllBureausResponse
     * @throws GetRawAllBureausFault
     */
    @WebMethod(action = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1/getRawAllBureaus")
    @WebResult(name = "getRawAllBureausResponse", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getRawAllBureaus_OutputPart")
    public GetRawAllBureausResponse getRawAllBureaus(
        @WebParam(name = "getRawAllBureaus", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getRawAllBureaus_InputPart")
        GetRawAllBureaus getRawAllBureausInputPart)
        throws GetRawAllBureausFault
    ;

    /**
     * 
     * @param getMISMOAllApplicantsInputPart
     * @return
     *     returns com.gdslink.mpmerge.santander.soap.GetMISMOAllApplicantsResponse
     * @throws GetMISMOAllApplicantsFault
     */
    @WebMethod(action = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXWS/v1/getMISMOAllApplicants")
    @WebResult(name = "getMISMOAllApplicantsResponse", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getMISMOAllApplicants_OutputPart")
    public GetMISMOAllApplicantsResponse getMISMOAllApplicants(
        @WebParam(name = "getMISMOAllApplicants", targetNamespace = "http://www.isban.es/webservices/GESTION/Gestion_m/F_mtxcor_gestion_m/intranet/MTXSOVWS/v1", partName = "getMISMOAllApplicants_InputPart")
        GetMISMOAllApplicants getMISMOAllApplicantsInputPart)
        throws GetMISMOAllApplicantsFault
    ;

}
